insert into achievement (name, type) values ("Chicken egg","egg");
insert into achievement (name, type) values ("Giant ant egg","egg");
insert into achievement (name, type) values ("Killer bee egg","egg");
insert into achievement (name, type) values ("Soldier ant egg","egg");
insert into achievement (name, type) values ("Fire ant egg","egg");
insert into achievement (name, type) values ("Queen bee egg","egg");
insert into achievement (name, type) values ("Cockatrice egg","egg");
insert into achievement (name, type) values ("Pyrolisk egg","egg");
insert into achievement (name, type) values ("Gargoyle egg","egg");
insert into achievement (name, type) values ("Winged gargoyle egg","egg");
insert into achievement (name, type) values ("Cave spider egg","egg");
insert into achievement (name, type) values ("Centipede egg","egg");
insert into achievement (name, type) values ("Giant spider egg","egg");
insert into achievement (name, type) values ("Scorpion egg","egg");
insert into achievement (name, type) values ("Long worm egg","egg");
insert into achievement (name, type) values ("Purple worm egg","egg");
insert into achievement (name, type) values ("Garter snake egg","egg");
insert into achievement (name, type) values ("Snake egg","egg");
insert into achievement (name, type) values ("Water moccasin egg","egg");
insert into achievement (name, type) values ("Pit viper egg","egg");
insert into achievement (name, type) values ("Python egg","egg");
insert into achievement (name, type) values ("Cobra egg","egg");
insert into achievement (name, type) values ("Piranha egg","egg");
insert into achievement (name, type) values ("Shark egg","egg");
insert into achievement (name, type) values ("Giant eel egg","egg");
insert into achievement (name, type) values ("Electric eel egg","egg");
insert into achievement (name, type) values ("Crocodile egg","egg");
insert into achievement (name, type) values ("Gray dragon egg","egg");
insert into achievement (name, type) values ("Silver dragon egg","egg");
insert into achievement (name, type) values ("Red dragon egg","egg");
insert into achievement (name, type) values ("White dragon egg","egg");
insert into achievement (name, type) values ("Orange dragon egg","egg");
insert into achievement (name, type) values ("Black dragon egg","egg");
insert into achievement (name, type) values ("Blue dragon egg","egg");
insert into achievement (name, type) values ("Green dragon egg","egg");
insert into achievement (name, type) values ("Yellow dragon egg","egg");
insert into achievement (name, type) values ("Red naga egg","egg");
insert into achievement (name, type) values ("Black naga egg","egg");
insert into achievement (name, type) values ("Golden naga egg","egg");
insert into achievement (name, type) values ("Guardian naga egg","egg");
insert into achievement (name, type) values ("Black dyed egg","egg");
insert into achievement (name, type) values ("Blue dyed egg","egg");
insert into achievement (name, type) values ("Bright blue dyed egg","egg");
insert into achievement (name, type) values ("Red dyed egg","egg");
insert into achievement (name, type) values ("Pink dyed egg","egg");
insert into achievement (name, type) values ("Orange dyed egg","egg");
insert into achievement (name, type) values ("Bright pink dyed egg","egg");
insert into achievement (name, type) values ("Green dyed egg","egg");
insert into achievement (name, type) values ("Blue-green dyed egg","egg");
insert into achievement (name, type) values ("Bright green dyed egg","egg");
insert into achievement (name, type) values ("Bright blue-green dyed egg","egg");
insert into achievement (name, type) values ("Brown dyed egg","egg");
insert into achievement (name, type) values ("Gray dyed egg","egg");
insert into achievement (name, type) values ("Yellow dyed egg","egg");
insert into achievement (name, type) values ("Chocolate egg","egg");
insert into achievement (name, type) values ("Golden egg","egg");
